package com.args;

import com.common.Annotation;

import java.io.Serializable;

public class MHBDiscoveryArgs implements Serializable {
    @Annotation("input file,mhap.gz format,generated by mHapTools and indexe")
    public String mHapPath = "";
    @Annotation("barcode ID file")
    public String bcFile = "";
    @Annotation("genomic CpG file, gz format and indexed")
    public String cpgPath = "";
    @Annotation("one region, in the format of chr:start-end")
    public String region = "";
    @Annotation("input BED file")
    public String bedFile = "";
    @Annotation("size of core window")
    public Integer window = 5;
    @Annotation("R square cutoff")
    public Double r2 = 0.5;
    @Annotation("P value cutoff")
    public Double pvalue = 0.05;
    @Annotation("output directory, created in advance")
    public String outputDir = "";
    @Annotation("prefix of the output file(s)")
    public String tag = "MHBDiscovery.out";
    @Annotation("whether output matrics for QC")
    public boolean qcFlag = false;

    public String getmHapPath() {
        return mHapPath;
    }

    public void setmHapPath(String mHapPath) {
        this.mHapPath = mHapPath;
    }

    public String getBedFile() {
        return bedFile;
    }

    public void setBedFile(String bedFile) {
        this.bedFile = bedFile;
    }

    public String getBcFile() {
        return bcFile;
    }

    public void setBcFile(String bcFile) {
        this.bcFile = bcFile;
    }

    public String getCpgPath() {
        return cpgPath;
    }

    public void setCpgPath(String cpgPath) {
        this.cpgPath = cpgPath;
    }

    public String getRegion() {
        return region;
    }

    public void setRegion(String region) {
        this.region = region;
    }

    public Integer getWindow() {
        return window;
    }

    public void setWindow(Integer window) {
        this.window = window;
    }

    public Double getR2() {
        return r2;
    }

    public void setR2(Double r2) {
        this.r2 = r2;
    }

    public Double getPvalue() {
        return pvalue;
    }

    public void setPvalue(Double pvalue) {
        this.pvalue = pvalue;
    }

    public String getOutputDir() {
        return outputDir;
    }

    public void setOutputDir(String outputDir) {
        this.outputDir = outputDir;
    }

    public String getTag() {
        return tag;
    }

    public void setTag(String tag) {
        this.tag = tag;
    }

    public boolean isQcFlag() {
        return qcFlag;
    }

    public void setQcFlag(boolean qcFlag) {
        this.qcFlag = qcFlag;
    }
}
