package com.args;

import com.common.Annotation;

import java.io.Serializable;

public class R2Args implements Serializable {
    @Annotation("input file,mhap.gz format,generated by mHapTools and indexed")
    public String mhapPath = "";
    @Annotation("genomic CpG file, gz format and indexed")
    public String cpgPath = "";
    @Annotation("one region, in the format of chr:start-end")
    public String region = "";
    @Annotation("barcode file")
    public String bcFile = "";
    @Annotation("output directory, created in advance")
    public String outputDir = "";
    @Annotation("prefix of the output file(s)")
    public String tag = "R2.out";
    @Annotation("plot linkage disequilibrium patterns of pair-wise CpGs")
    public boolean mhapView = false;
    @Annotation("strand information, one of plus, minus and both [both]")
    public String strand = "both";
    @Annotation("indicates whether generate a file in longrange format")
    public boolean longrange = false;
    @Annotation("input BED file")
    public String bedFile = "";

    public String getMhapPath() {
        return mhapPath;
    }

    public void setMhapPath(String mhapPath) {
        this.mhapPath = mhapPath;
    }

    public String getCpgPath() {
        return cpgPath;
    }

    public void setCpgPath(String cpgPath) {
        this.cpgPath = cpgPath;
    }

    public String getRegion() {
        return region;
    }

    public void setRegion(String region) {
        this.region = region;
    }

    public String getBcFile() { return bcFile; }

    public void setBcFile(String bcFile) { this.bcFile = bcFile; }

    public String getOutputDir() {
        return outputDir;
    }

    public void setOutputDir(String outputDir) {
        this.outputDir = outputDir;
    }

    public String getTag() {
        return tag;
    }

    public void setTag(String tag) {
        this.tag = tag;
    }

    public boolean isMhapView() {
        return mhapView;
    }

    public void setMhapView(boolean mhapView) {
        this.mhapView = mhapView;
    }

    public String getStrand() {
        return strand;
    }

    public void setStrand(String strand) {
        this.strand = strand;
    }

    public boolean isLongrange() {
        return longrange;
    }

    public void setLongrange(boolean longrange) {
        this.longrange = longrange;
    }

    public String getBedFile() {
        return bedFile;
    }

    public void setBedFile(String bedFile) {
        this.bedFile = bedFile;
    }
}
