package com.args;

import java.io.Serializable;

public class R2Args implements Serializable {

    public String mhapPath; // input file, mhap.gz format, generated by mHapTools and indexed
    public String cpgPath; // genomic CpG file, gz format and Indexed
    public String region; // one region, in the format of chr:start-end
    public String bcFile;
    public String outputDir = ""; // output directory, created in advance
    public String tag; // prefix of the output files
    public boolean mhapView = false; // plot linkage disequilibrium patterns of pair-wise CpGs
    public String strand; // strand information, one of plus, minus and both [both]
    public boolean longrange = false; // indicates whether generate a file in longrange format
    public String bedFile; // BED file

    public String getMhapPath() {
        return mhapPath;
    }

    public void setMhapPath(String mhapPath) {
        this.mhapPath = mhapPath;
    }

    public String getCpgPath() {
        return cpgPath;
    }

    public void setCpgPath(String cpgPath) {
        this.cpgPath = cpgPath;
    }

    public String getRegion() {
        return region;
    }

    public void setRegion(String region) {
        this.region = region;
    }

    public String getBcFile() { return bcFile; }

    public void setBcFile(String bcFile) { this.bcFile = bcFile; }

    public String getOutputDir() {
        return outputDir;
    }

    public void setOutputDir(String outputDir) {
        this.outputDir = outputDir;
    }

    public String getTag() {
        return tag;
    }

    public void setTag(String tag) {
        this.tag = tag;
    }

    public boolean isMhapView() {
        return mhapView;
    }

    public void setMhapView(boolean mhapView) {
        this.mhapView = mhapView;
    }

    public String getStrand() {
        return strand;
    }

    public void setStrand(String strand) {
        this.strand = strand;
    }

    public boolean isLongrange() {
        return longrange;
    }

    public void setLongrange(boolean longrange) {
        this.longrange = longrange;
    }

    public String getBedFile() {
        return bedFile;
    }

    public void setBedFile(String bedFile) {
        this.bedFile = bedFile;
    }
}
